--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
  - !ruby/struct:SM::Flow::P 
    body: The standard configuration object for gems.
full_name: Gem::configuration
is_singleton: true
name: configuration
params: ()
visibility: public
