--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
  - !ruby/struct:SM::Flow::P 
    body: The path to standard location of the user's .gemrc file.
full_name: Gem::config_file
is_singleton: true
name: config_file
params: ()
visibility: public
