--- !ruby/object:RI::ClassDescription 
attributes: 
  - !ruby/object:RI::Attribute 
    comment: 
      - !ruby/struct:SM::Flow::P 
        body: List of arguments supplied to the config file object.
    name: args
    rw: R
  - !ruby/object:RI::Attribute 
    comment: 
      - !ruby/struct:SM::Flow::P 
        body: True if we print backtraces on errors.
    name: backtrace
    rw: W
  - !ruby/object:RI::Attribute 
    comment: 
      - !ruby/struct:SM::Flow::P 
        body: True if we are benchmarking this run.
    name: benchmark
    rw: RW
  - !ruby/object:RI::Attribute 
    comment: 
      - !ruby/struct:SM::Flow::P 
        body: Bulk threshold value. If the number of missing gems are above this threshold value, then a bulk download technique is used.
    name: bulk_threshold
    rw: RW
  - !ruby/object:RI::Attribute 
    comment: 
    name: hash
    rw: R
  - !ruby/object:RI::Attribute 
    comment: 
    name: home
    rw: RW
  - !ruby/object:RI::Attribute 
    comment: 
      - !ruby/struct:SM::Flow::P 
        body: Where to look for gems
    name: path
    rw: RW
  - !ruby/object:RI::Attribute 
    comment: 
      - !ruby/struct:SM::Flow::P 
        body: True if we want to update the SourceInfoCache every time, false otherwise
    name: update_sources
    rw: RW
  - !ruby/object:RI::Attribute 
    comment: 
      - !ruby/struct:SM::Flow::P 
        body: "Verbose level of output:"
      - !ruby/object:SM::Flow::LIST 
        contents: 
          - !ruby/struct:SM::Flow::LI 
            label: "*"
            body: false -- No output
          - !ruby/struct:SM::Flow::LI 
            label: "*"
            body: true -- Normal output
          - !ruby/struct:SM::Flow::LI 
            label: "*"
            body: ":loud -- Extra output"
        type: :BULLET
    name: verbose
    rw: RW
class_methods: 
  - !ruby/object:RI::MethodSummary 
    name: new
comment: 
  - !ruby/struct:SM::Flow::P 
    body: Store the gem command options specified in the configuration file. The config file object acts much like a hash.
constants: 
  - !ruby/object:RI::Constant 
    comment: 
    name: DEFAULT_BACKTRACE
    value: "false"
  - !ruby/object:RI::Constant 
    comment: 
    name: DEFAULT_BENCHMARK
    value: "false"
  - !ruby/object:RI::Constant 
    comment: 
    name: DEFAULT_BULK_THRESHOLD
    value: "1000"
  - !ruby/object:RI::Constant 
    comment: 
    name: DEFAULT_VERBOSITY
    value: "true"
  - !ruby/object:RI::Constant 
    comment: 
    name: DEFAULT_UPDATE_SOURCES
    value: "true"
  - !ruby/object:RI::Constant 
    comment: 
      - !ruby/struct:SM::Flow::P 
        body: For Ruby packagers to set configuration defaults. Set in rubygems/defaults/operating_system.rb
    name: OPERATING_SYSTEM_DEFAULTS
    value: "{}"
  - !ruby/object:RI::Constant 
    comment: 
      - !ruby/struct:SM::Flow::P 
        body: For Ruby implementers to set configuration defaults. Set in rubygems/defaults/#{RUBY_ENGINE}.rb
    name: PLATFORM_DEFAULTS
    value: "{}"
  - !ruby/object:RI::Constant 
    comment: 
    name: CSIDL_COMMON_APPDATA
    value: "0x0023"
  - !ruby/object:RI::Constant 
    comment: 
    name: SHGetFolderPath
    value: Win32API.new 'shell32', 'SHGetFolderPath', 'PLPLP',                                        'L', :stdcall
  - !ruby/object:RI::Constant 
    comment: 
    name: SHGetFolderPath
    value: Win32API.new 'shell32', 'SHGetFolderPath', 'LLLLP',                                        'L'
  - !ruby/object:RI::Constant 
    comment: 
    name: SYSTEM_WIDE_CONFIG_FILE
    value: File.join system_config_path, 'gemrc'
full_name: Gem::ConfigFile
includes: []

instance_methods: 
  - !ruby/object:RI::MethodSummary 
    name: "[]"
  - !ruby/object:RI::MethodSummary 
    name: "[]="
  - !ruby/object:RI::MethodSummary 
    name: backtrace
  - !ruby/object:RI::MethodSummary 
    name: config_file_name
  - !ruby/object:RI::MethodSummary 
    name: each
  - !ruby/object:RI::MethodSummary 
    name: handle_arguments
  - !ruby/object:RI::MethodSummary 
    name: load_file
  - !ruby/object:RI::MethodSummary 
    name: really_verbose
  - !ruby/object:RI::MethodSummary 
    name: write
name: ConfigFile
superclass: Object
