--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
  - !ruby/struct:SM::Flow::P 
    body: Return the path to the data directory associated with the given package name. Normally this is just &quot;#{Config::CONFIG['datadir']}/#{package_name}&quot;, but may be modified by packages like RubyGems to handle versioned data directories.
full_name: Config::datadir
is_singleton: true
name: datadir
params: (package_name)
visibility: public
